package com.example.cuadernodedeku.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006B59)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF5AF9EC)
val md_theme_light_onPrimaryContainer = Color(0xFF00201E)
val md_theme_light_secondary = Color(0xFF006A64)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF7BF8D9)
val md_theme_light_onSecondaryContainer = Color(0xFF002019)
val md_theme_light_tertiary = Color(0xFF85468C)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD6FE)
val md_theme_light_onTertiaryContainer = Color(0xFF35003F)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF0A0C10)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF0A0C10)
val md_theme_light_surfaceVariant = Color(0xFFDAE5E2)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4947)
val md_theme_light_outline = Color(0xFF6F7977)
val md_theme_light_inverseOnSurface = Color(0xFFFFEDE9)
val md_theme_light_inverseSurface = Color(0xFF0A0C10)
val md_theme_light_inversePrimary = Color(0xFF2FDDD0)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006A64)
val md_theme_light_outlineVariant = Color(0xFFBEC9C6)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF2FDDD0)
val md_theme_dark_onPrimary = Color(0xFF003733)
val md_theme_dark_primaryContainer = Color(0xFF00504B)
val md_theme_dark_onPrimaryContainer = Color(0xFF5AF9EC)
val md_theme_dark_secondary = Color(0xFF5CDBBD)
val md_theme_dark_onSecondary = Color(0xFF00382D)
val md_theme_dark_secondaryContainer = Color(0xFF005142)
val md_theme_dark_onSecondaryContainer = Color(0xFF7BF8D9)
val md_theme_dark_tertiary = Color(0xFFF7ADFC)
val md_theme_dark_onTertiary = Color(0xFF51145A)
val md_theme_dark_tertiaryContainer = Color(0xFF6A2E73)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD6FE)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF0A0C10)
val md_theme_dark_onBackground = Color(0xFFFFDAD4)
val md_theme_dark_surface = Color(0xFF0A0C10)
val md_theme_dark_onSurface = Color(0xFFFFDAD4)
val md_theme_dark_surfaceVariant = Color(0xFF3F4947)
val md_theme_dark_onSurfaceVariant = Color(0xFFBEC9C6)
val md_theme_dark_outline = Color(0xFF899391)
val md_theme_dark_inverseOnSurface = Color(0xFF0A0C10)
val md_theme_dark_inverseSurface = Color(0xFFFFDAD4)
val md_theme_dark_inversePrimary = Color(0xFF006A64)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF2FDDD0)
val md_theme_dark_outlineVariant = Color(0xFF3F4947)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF01CEC2)